### ISSUE TITLE
#39397: Include customer number by default

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#10]
The customer number should be included by default in
a.) 'AR--Reports--Transactions'
b.) 'AR--Reports--Outstanding'

![bildschirmfoto 2015-06-01 um 15 06 01](https://cloud.githubusercontent.com/assets/100664/7913376/c9733912-086f-11e5-84e7-d1afe047b550.png)

**Comment by ledger123** [comment]
This is done.

**Comment by sweitmann** [comment]
Fantastic. Thanks Armaghan. I will close this ticket now.
