### ISSUE TITLE
#38555: Sort AR and AP transactions by 'paid' column

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#12]
After running 'AR/AP--Transactions' report for 'Open' transactions, it should be possible to sort the report by 'paid' column. The report should then show the highest overpaid transactions first, followed by underpaid and undpaid invoices.

![bildschirmfoto 2015-06-01 um 15 23 42](https://cloud.githubusercontent.com/assets/100664/7913682/382e8454-0872-11e5-924c-a3281e9978b4.png)

**Comment by ledger123** [comment]
This is done and code pushed.

Regards

**Comment by sweitmann** [comment]
Fantastic! Thanks, Armaghan. I will close this ticket now.
