### ISSUE TITLE
#38499: Department Income Statement - No department by default + Select all option

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#13]
The Department Income Statement report should not have any department selected by default. Instead there could be an option to 'select all' if necessary. 

![bildschirmfoto 2015-06-01 um 15 32 25](https://cloud.githubusercontent.com/assets/100664/7913878/73eeaf86-0873-11e5-816e-cada094e1a87.png)

**Comment by ledger123** [comment]
This is done and pushed.

Regards

**Comment by sweitmann** [comment]
Cool! Thanks, Armaghan. I will close this ticket now.
