### ISSUE TITLE
#38262: Add 'History' button to Edit Customer/Vendor screen

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#14]
Add a 'History' button in the Edit Customer/Vendor screens that links to 'AR/AP--Transactions' reports including 'Due' in report

![bildschirmfoto 2015-06-01 um 16 30 36](https://cloud.githubusercontent.com/assets/100664/7915100/93c9eeee-087b-11e5-8907-99ca524168ae.png)

![bildschirmfoto 2015-06-01 um 16 34 09](https://cloud.githubusercontent.com/assets/100664/7915156/0fa8b928-087c-11e5-8031-d1ecab86e540.png)

**Comment by ledger123** [comment]
I have added this feature with 'Report' button. 'History' procedure is already in use in the script so it would require some more code to use that button.

**Comment by sweitmann** [comment]
Cool. Very nice solution! I will close this ticket now.
