### ISSUE TITLE
#38197: Hit enter in 'General Ledger-Add Transaction' should focus on list of accounts

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#15]
Hitting the enter key in 'General Ledger-Add Transaction' should focus cursor on list of accounts, not on debit column.

![bildschirmfoto 2015-06-01 um 16 39 20](https://cloud.githubusercontent.com/assets/100664/7915291/d795020c-087c-11e5-8a16-6e187c295307.png)

![bildschirmfoto 2015-06-01 um 16 39 39](https://cloud.githubusercontent.com/assets/100664/7915301/e358829e-087c-11e5-85ab-36f7a0460840.png)

**Comment by ledger123** [comment]
Done.

**Comment by sweitmann** [comment]
Wonderful. Perfect, thanks Armaghan. Will close this ticket now.
