### ISSUE TITLE
#36016: Link Customer/Vendor to department

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#16]
It should also be possible to link a Customer/Vendor to a certain department.

![bildschirmfoto 2015-06-01 um 16 45 34](https://cloud.githubusercontent.com/assets/100664/7915419/ab07e51e-087d-11e5-828a-100f5b69e8cd.png)

**Comment by ledger123** [comment]
It is now possible. :)
Done and updated.

**Comment by sweitmann** [comment]
Thanks, Armaghan. Is it possible to also use this information in AR/AP transactions, so that if a customer/vendor is linked to a certain department, this department is automatically selected when a new AR/AP transaction for the specific customer/vendor is entered?

![bildschirmfoto 2015-06-23 um 11 57 25](https://cloud.githubusercontent.com/assets/100664/8303574/151a0018-199f-11e5-912b-371db341435c.png)

**Comment by ledger123** [comment]
Hi Sebastian,

Yes, I have done this and updated github.

Now whenever you will select a new customers, its department from its profile will become default but can be changed by the user entering the transaction.

I have done it in AR/AP transactions as you said. But why not in invoices too?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, sorry for being unclear; no reason for not adjusting this in invoices too and let me know when you are done. I will then test and close this ticket. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I was about to work on it and found out that the change for transactions also works for invoices. So no further work needed to make it work for invoices.

Kindly do the testing and let me know if you find any issues.

Regards

**Comment by sweitmann** [comment]
Perfekt, thanks Armaghan. I will close this ticket now.

Regards
