### ISSUE TITLE
Sorting Cutomers/Vendors in AP/AR Modules

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#20]
In the RMA version of SQL-Ledger you can see both Company Name & Contact Person for each Customer/Vendor that appears in the AP/AR module drop down menus. 

![bildschirmfoto 2015-07-09 um 18 15 24](https://cloud.githubusercontent.com/assets/100664/8600621/07e040ea-2667-11e5-95d2-d7b9fb39c507.png)

As it is now the list in the drop down menu is sorted by Company Name, but not subsequently by Contact Person. Could you please adjust this, so that it sorts by Company Name and subsequently by Contact Person?

Regards

**Comment by ledger123** [comment]
This is done and code is pushed to github.

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan! Cool. Closing this ticket now.

**Comment by sweitmann** [comment]
Hi Armaghan,

starting Saturday this week, I will be taking a week off from work. The kids are in Italy with Deborah's mother and Deborah and I will be joining them there this weekend. Really looking forward to a weeks holiday with my loved ones.

Nils is returning on August the 7th and I would like to try to have fixed his issues by then, if possible.

That would be the following issues:

1.) Re-design "Line Tax" version

2.) #38499 Department Income Statement- No department by default + Select all option

3.) #38555: Sort AR and AP transactions by 'paid' column

4.) #39137: Print and Post - Button should also handle PDF to Screen

5.) Reconsiliation - show balance as sum of un-reconciled transactions

6.) DATEV Export module

Once we have sorted out these six issues, I think we could take a break from solving open issues and you could start looking into mojolicious instead, because Nils will then also need to implement all our latest fixes into the official RMA-Version. And he is quite a bit behind the develop branch now.

Starting from July I am now crediting you 200 CHF per month again in the SQL-Ledger Network Association. I would like to use that small amount of energy not to forget about and also keep on developing our rel3 version. I have the feeling that rel3 has suffered a bit from my full time position at RMA. I feel it has been a little neglected lately.

My idea is therefore to involve and ask my friend Miguel Santos to handle the tickets for our rel3 version and see to that we don't neglect it too much. I would like to connect you and him and let him keep track and follow up on our rel3 road map.

What do you think? Does that sound ok to you?

Regards
Sebastian










>

**Comment by ledger123** [comment]
Hi Sebastian,

On Monday, July 13, 2015, Sebastian Weitmann <notifications@github.com>
wrote:

> Hi Armaghan,
>
> starting Saturday this week, I will be taking a week off from work. The
> kids are in Italy with Deborah's mother and Deborah and I will be joining
> them there this weekend. Really looking forward to a weeks holiday with my
> loved ones.
>

I see that you are working even on weekends now a days so it is a well
deserved break.


>
> Nils is returning on August the 7th and I would like to try to have fixed
> his issues by then, if possible.
>
> That would be the following issues:
>
> 1.) Re-design "Line Tax" version
>
> 2.) #38499 Department Income Statement- No department by default + Select
> all option
>
> 3.) #38555: Sort AR and AP transactions by 'paid' column
>
> 4.) #39137: Print and Post - Button should also handle PDF to Screen
>
> 5.) Reconsiliation - show balance as sum of un-reconciled transactions
>
> 6.) DATEV Export module
>
>
Three of them done. The other two should hopefully be done today if I don't
get stuck in some coding issue.


> Once we have sorted out these six issues, I think we could take a break
> from solving open issues and you could start looking into mojolicious
> instead, because Nils will then also need to implement all our latest fixes
> into the official RMA-Version. And he is quite a bit behind the develop
> branch now.
>

That will be great.


>
> Starting from July I am now crediting you 200 CHF per month again in the
> SQL-Ledger Network Association. I would like to use that small amount of
> energy not to forget about and also keep on developing our rel3 version. I
> have the feeling that rel3 has suffered a bit from my full time position at
> RMA. I feel it has been a little neglected lately.
>

Grateful for this but please don't start this. This will put too much
pressure on me to do work on rel3 which is not possible right now, at least
for a month or two. I will be happy to accept as soon as I start working on
rel3.

That said, we can always enhance and update rel3 with some particular
requirement whenever you have a business need from a client and it can be
done as urgently as you may need.


>
> My idea is therefore to involve and ask my friend Miguel Santos to handle
> the tickets for our rel3 version and see to that we don't neglect it too
> much. I would like to connect you and him and let him keep track and follow
> up on our rel3 road map.
>
> What do you think? Does that sound ok to you?
>

Do I also know Miguel Santos from some past discussion? I could not find.
His contribution will be regarding coding or testing? Coding will be indeed
a great help and I can setup his access to the repository as required.
Testing is also great when I shall start work on rel3.

Regards
