### ISSUE TITLE
Re-design "Line Tax" version

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#3]
Move 'description' and 'project' fileds in AR and AP modules 'Add transaction' to second row.

**Comment by ledger123** [comment]
This is done and code pushed.

**Comment by sweitmann** [comment]
Sorry, my mistake. I wasn't very clear on this one. The 'Line Item' and 'Projects' fields should only be moved to the second row, if 'Line Tax' has been activated in the defaults. As it is now, 'Line Tax' is on the second row, even if 'Line Tax' is not activated.

Would it also be possible to add the missing field labels?

![bildschirmfoto 2015-06-23 um 16 05 25](https://cloud.githubusercontent.com/assets/100664/8307935/f9a62a14-19c1-11e5-83b2-7346fbc07e24.png)

**Comment by sweitmann** [comment]
Thanks Armaghan, your latest proposal for AP / AR transactions has now been approved. In regard to the labels, could we perhaps try to write "Account / Line Item" and "Tax / Project" at the top instead of just "Account" and "Tax". It would keep the screen nice and clean as you suggested, but still give the user a hint that the mentioned information can be entered below. Of course, the "Tax / Project" should then only appear if the user has activated projects.

**Comment by ledger123** [comment]
This is fixed as described and code pushed.

**Comment by sweitmann** [comment]
Fantastic, thanks Armaghan!

Now we need to do the same re-design in the 'General Ledger--Add Transaction' screen. 

My proposal is two rows for each enty.

a.) First part:
![bildschirmfoto 2015-07-03 um 12 53 49](https://cloud.githubusercontent.com/assets/100664/8498118/785aedcc-2183-11e5-81ba-cabb0e1e5afc.png)

b.) Move to second row:
![bildschirmfoto 2015-07-03 um 13 02 44](https://cloud.githubusercontent.com/assets/100664/8498147/e5d559c8-2183-11e5-9a89-9fd8df014510.png)

Can we try this to see how it would look and feel? What is your opinion?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Due to an unplanned travel I will not sending new updates this week. Will
be back by Saturday and will start sending again.
Regards

**Comment by ledger123** [comment]
This is done and pushed. Have a look.

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan. I'm afraid it looks to messy as I suggested at first. What do you think? Perhaps we could try something like this instead?

![bildschirmfoto 2015-07-14 um 15 41 16](https://cloud.githubusercontent.com/assets/100664/8674570/0ad2a7e4-2a3f-11e5-89b2-399e6310c45f.png)

**Comment by ledger123** [comment]
Hi Sebastian,

Do you think we need to take Thomas feedback on this too before doing it?

If not, then I shall do it now.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Thomas gave me his approval for this latest design proposal above yesterday, so he is already onboard. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done and pushed to github. Have a look and confirm if everything is ok.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

fantastic, thanks! It looks really good now. Only two small things:

a.) When I use the tab key the cursor jumps from Account -> Memo -> Source -> Debit -> Credit etc. This means it jumps between the lines. Would it be possible to make it jump from Account -> Debit -> Credit -> Tax Included -> Tax Amount -> Memo -> Source -> Project -> Account ... instead?

2.) We could save some more width if we moved the total tax amount below the tax amount fields instead? Can this be done easily? 

![bildschirmfoto 2015-07-31 um 17 09 25](https://cloud.githubusercontent.com/assets/100664/9010392/f42455b8-37a6-11e5-950c-36786ca9138d.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This has been done and pushed to github.

Regards

**Comment by sweitmann** [comment]
Moved to ledger123/runmyaccounts issues list.
