### ISSUE TITLE
Cosmetic rounding issue in AR and AP transactions

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#5]
![bildschirmfoto 2015-06-01 um 11 53 01](https://cloud.githubusercontent.com/assets/100664/7910439/e5b97fac-0854-11e5-9a30-50d02733b6d2.png)

**Comment by ledger123** [comment]
Hi Sebastian,

This is already done in https://github.com/ledger123/runmyaccounts/commit/63a719dab1

Kindly test and let me know if you still face any problem.

Regards

**Comment by sweitmann** [comment]
You are right, sorry. Closing this ticket now.
