### ISSUE TITLE
Reconsiliation - show balance as sum of un-reconciled transactions

### ISSUE THREAD

**Issue by sweitmann** [ledger123/ledger123#6]
I have entered some bookings in app.sql-ledger-network.com to replicate the issue.

You will can see the problem (bug) there if you do the following:

a.) Run 'Cash--Reconciliation' and select the account "1205--Bank Foreign Currency Account"

b.) Click "Continue" and note the "Beginning Balance" (0,81)

c.) Now go back and select the period "April 2015" and click "Continue" again.

d.) This time note the correct "Beginning Balance" (0,00)

Conclusion: Unless a period is selected, the report has a problem with "FX Adjustment" bookings (GL-12)

**Comment by ledger123** [comment]
Hi Sebastian,

This is fixed in 'rel3' since the test data was in rel3. 

Please confirm it this is ok then I shall port it to RMA version.

Regards

**Comment by sweitmann** [comment]
Fantastic. Thanks, Armaghan. Problem solved. Closing this ticket now.
